version: '3'

services:
  wikibase:
    image: wikibase/wikibase:1.35-base
    entrypoint: /code-repo/docker-compose-entry.sh
    volumes:
      - ./:/code-repo
      - ./settings/${PROFILE_SETTINGS}.sh:/code-settings.sh
    links:
      - mysql
    ports:
     - "8181:80"
    depends_on:
    - mysql
  mysql:
    image: mariadb:10.3
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: 'my_wiki'
      MYSQL_USER: 'wikiuser'
      MYSQL_PASSWORD: 'sqlpass'