version: '3'

services:
  wikibase1:
    image: ${PROFILE_IMAGE}
    entrypoint: /code-repo/docker-compose-entry1.sh
    volumes:
      - ./:/code-repo
      - ./settings/${PROFILE_SETTINGS}.sh:/code-settings.sh
      - ./apache.extra.conf:/etc/apache2/conf-available/wb-profile.extra.conf
      - type: bind
        source: ./modifications/wikibase-fast-import-proof-of-concept-2022/${PROFILE_IMAGE}/extension-repo.json
        target: /var/www/html/extensions/Wikibase/extension-repo.json
      - type: bind
        source: ./modifications/wikibase-fast-import-proof-of-concept-2022/${PROFILE_IMAGE}/FastImport.php
        target: /var/www/html/extensions/Wikibase/repo/includes/Api/FastImport.php

    links:
      - mysql
    ports:
     - "8181:80"
    depends_on:
    - mysql
  wikibase2:
    image: ${PROFILE_IMAGE}
    entrypoint: /code-repo/docker-compose-entry2.sh
    volumes:
      - ./:/code-repo
      - ./settings/${PROFILE_SETTINGS}.sh:/code-settings.sh
      - ./apache.extra.conf:/etc/apache2/conf-available/wb-profile.extra.conf
      - type: bind
        source: ./modifications/wikibase-fast-import-proof-of-concept-2022/${PROFILE_IMAGE}/extension-repo.json
        target: /var/www/html/extensions/Wikibase/extension-repo.json
      - type: bind
        source: ./modifications/wikibase-fast-import-proof-of-concept-2022/${PROFILE_IMAGE}/FastImport.php
        target: /var/www/html/extensions/Wikibase/repo/includes/Api/FastImport.php
    links:
      - mysql
    ports:
     - "8182:80"
    depends_on:
    - mysql
  # wikibase3:
  #   image: ${PROFILE_IMAGE}
  #   entrypoint: /code-repo/docker-compose-entry2.sh
  #   volumes:
  #     - ./:/code-repo
  #     - ./settings/${PROFILE_SETTINGS}.sh:/code-settings.sh
  #   links:
  #     - mysql
  #   ports:
  #    - "8183:80"
  #   depends_on:
  #   - mysql
  mysql:
    image: ${PROFILE_SQL}
    volumes:
      - ./my.extra.cnf:/etc/mysql/conf.d/wb-profile.extra.cnf
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: 'my_wiki'
      MYSQL_USER: 'wikiuser'
      MYSQL_PASSWORD: 'sqlpass'