on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  profile:
    strategy:
      fail-fast: false
      matrix:
        instances:
          - 1
          - 2
        async:
          - 1
          - 5
          - 60
        images:
          # - wikibase/wikibase:1.33-base # Would require vendor/autoload in Wikibase to work
          # - wikibase/wikibase:1.34-base # Would require vendor/autoload in Wikibase to work
          # - wikibase/wikibase:1.35-base # Would require vendor/autoload in Wikibase to work
          # - wikibase/wikibase:1.36.4-wmde.8 # Pre extension Registration
          # - wikibase/wikibase:1.37.6-wmde.9 # Pre extension Registration
          # - wikibase/wikibase:1.38.5-wmde.10 # Pre extension Registration
          - wikibase/wikibase:1.39.1-wmde.11 # Requires wfLoadExtension
        sql:
          # - mariadb:10.3 # No real difference between 10.3 and 10.5 mariadb, so just use the newest one
          # - mariadb:10.5
          # - mariadb:10.6
          # - mariadb:10.7
          # - mariadb:10.8
          - mariadb:10.9
          # - mysql:5.7 # MariaDB seems to generally be the faster choice...
          # - mysql:8.0 # Broken! and thus untested... (Probably because the install fails? :)
        settings:
          - default
          - lightweight
          # - mwCacheDirectory
          # - mwNoJobs
          # - wbNoChangesTable
          # - wbNewTerms
          # - wbOwnIdConnection
        loads:
          # - wbeditentity-2000EmptyItems
          # - wbeditentity-2000SingleTermItems
          # - wbeditentity-2000MultiTermItems
          - wbeditentity-2000FullishItems
          - wbfastimport-2000full-batch100
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run containers
        env:
          PROFILE_SETTINGS: ${{ matrix.settings }}
          PROFILE_IMAGE: ${{ matrix.images }}
          PROFILE_SQL: ${{ matrix.sql }}
        run: |
          docker-compose up -d mysql wikibase1
          ./docker-compose-wait1.sh
          docker-compose up -d wikibase2
          ./docker-compose-wait2.sh
          docker-compose up -d --force-recreate wikibase1
          ./docker-compose-wait1.sh
          sleep 5
      - name: Perform test
        run: |
          # If a file suffixed in -before exists, then run it first
          if [ -f ./loads/${{ matrix.loads }}-before.sh ]; then
            ASYNC=${{ matrix.async }} INSTANCES=${{ matrix.instances }} ./loads/${{ matrix.loads }}-before.sh
          fi
          date +%s >> start.out
          ASYNC=${{ matrix.async }} INSTANCES=${{ matrix.instances }} ./loads/${{ matrix.loads }}.sh
          date +%s >> stop.out
      - name: Output things
        run: |
          cat process.out
          docker-compose logs
      - name: Stop containers
        run: docker-compose down
      - name: Output Result
        id: output-calc
        run: |
          echo "Start time: " $(cat start.out)
          echo "Stop time: " $(cat stop.out)
          let length=$(cat stop.out)-$(cat start.out)
          SUCCESSES=$(cat process.out | grep -o success | wc -l)
          echo "Successfull calls: " $SUCCESSES
          echo "Elapsed time: " $length
          echo "::set-output name=elapsed::$(echo ${length})"
          echo "::set-output name=successes::$(echo ${SUCCESSES})"
          # https://docs.github.com/en/rest/reference/checks#annotations-items
          echo "[{\"title\":\"${{ matrix.settings }} ${{ matrix.loads }} Async:${{ matrix.async }} Instances:${{ matrix.instances }}\",\"message\":\"Elapsed time: ${length} Successes: ${SUCCESSES}\",\"path\":\".github/workflows/test.yml\",\"start_line\":1,\"end_line\":1,\"annotation_level\":\"notice\"}]" > annotations.json
      - name: Annotate
        uses: kibalabs/github-action-create-annotations@main
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          json-file-path: './annotations.json'
      # - name: Send result to IFTTT
      #   uses: "hugoalh/GitHubAction.SendToIFTTT@v2.0.0"
      #   with:
      #     webhook_eventname: "gha-wikibase-profile-result"
      #     webhook_key: "${{secrets.IFTTT_WEBHOOK_KEY}}"
      #     value1: ${{ github.ref }} ${{ github.run_id }} ${{ github.run_number }}
      #     value2: ${{ matrix.images }} ${{ matrix.settings }} ${{ matrix.loads }} ${{ matrix.sql }} ${{ matrix.async }} ${{ matrix.instances }} 
      #     value3: ${{ steps.output-calc.outputs.elapsed }} ${{ steps.output-calc.outputs.successes }}