on:
  push:
    branches:
      - main
jobs:
  profile:
    strategy:
      fail-fast: false
      matrix:
        image: 
          - wikibase/wikibase:1.33-base
#          - wikibase/wikibase:1.34-base
          - wikibase/wikibase:1.35-base
        settings: 
#          - default
          - mwNoJobs
#          - wbNoChangesTable
        loads:
#          - 2000EmptyItems
#          - 2000SingleTermItems
#          - 2000MultiTermItems
          - 2000FullishItems
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run containers
        run: PROFILE_SETTINGS=${{ matrix.settings }} PROFILE_IMAGE=${{ matrix.image }} docker-compose up -d
      - name: Wait for setup
        run: |
          ./docker-compose-wait.sh
          sleep 5
      - name: Perform test
        run: |
          date +%s >> start.out
          ./loads/${{ matrix.loads }}.sh
          date +%s >> stop.out
      - name: Stop containers
        run: docker-compose down
      - name: Output Result
        run: |
          echo "Start time: " $(cat start.out)
          echo "Stop time: " $(cat stop.out)
          let length=$(cat stop.out)-$(cat start.out)
          echo "Elapsed time: " $length
          # https://docs.github.com/en/rest/reference/checks#annotations-items
          echo "[{\"title\":\"${{ matrix.settings }} ${{ matrix.loads }}\",\"message\":\"Elapsed time: ${length}\",\"path\":\".github/workflows/test.yml\",\"start_line\":1,\"end_line\":1,\"annotation_level\":\"notice\"}]" > annotations.json
      - name: Annotate
        uses: kibalabs/github-action-create-annotations@main
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          json-file-path: './annotations.json'