on:
  push:
    branches:
      - main
jobs:
  profile:
    strategy:
      fail-fast: false
      matrix:
        settings: [default]
        loads: [10EmptyItems,100EmptyItems]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: PROFILE_SETTINGS=${{ matrix.settings }} docker-compose up -d
      - run: ./docker-compose-wait.sh
      - run: sleep 5
      - run: |
          date +%s >> start.out
          ./loads/${{ matrix.loads }}.sh
          date +%s >> stop.out
      - run: docker-compose down
      - run: |
          cat process.out
          cat start.out
          cat stop.out
          let length=$(cat stop.out)-$(cat start.out)